### ISSUE TITLE
Crashes on 3.1.0 On Dedicated server (cannot be cast as Playerentity

### ISSUE THREAD

**Issue by elibosley** [Shorepion/Magica-Infinitum-III#1]
Thank you for reporting an issue!
Please make sure to give answers for the following:

1) Which Modpack version are you using?
 3.1.0
2) Link to the crashlog (found in the crash-reports folder).
https://pastebin.com/QiNZmJ52
 
3) Detailed description of the issue and if possible pls attach images

No images - exploring the world as normal and loaded a chunk where presumable some mod was interfering with worldgen and tried to cast a player as a creeper / other mob. This has happened on two separate worlds - we disabled to bosses module (or tried to) as well as the hitmarkers as both of those were suspected of doing this, but we're out of ideas. 

4) Is the issue repeatable?
 
Should be repeatable if you just host a dedicated server and explore.

5) Do you know a possible fix for the issue?

I have no idea :(

**Comment by Shorepion** [comment]
**For the mana boost effect on non-player entity crash there is a fix:**
https://github.com/Mithion/Mana-And-Artifice/issues/82
The thing is that this M&A version is for **1.16.4** and requires Forge **35.1.1** or above. 
So I have to update the whole pack to **1.16.4**. 
Im currently testing if there will be problems in the transition from 1.16.3 to 1.16.4 concerning 1.16.3 created worlds.

There is also something with Apotheosis and 'BossItems'.
Must have a deeper look into that.
✌️

**Comment by Shorepion** [comment]
fixed in the latest update.

**Comment by Shorepion** [comment]
> will be fixed in the next update.

https://zupimages.net/up/20/52/xrtm.jpg "next update" ..
