### ISSUE TITLE
FML Early Loading Issue

### ISSUE THREAD

**Issue by thisisprobablyleo** [Shorepion/Magica-Infinitum-III#11]
Thank you for reporting an issue!
Please make sure to give answers for the following:

1) Which Modpack version are you using?
 Magica Infinitum III - 1.16.4-3.2.0.zip

2) Link to the crashlog (found in the crash-reports folder).
https://pastebin.com/3Nhe1xz5
 
3) Detailed description of the issue and if possible pls attach images
While initiating the FML early loading process, the loading screen halts early on and opens up vanilla minecraft. I've tried using another launcher, redownloading, restarting pc/twitch multiple times, using another version of forge, and raising/lowering my maximum allocated ram. Nothing works save for playing at version 3.1.1, and my friends can play the pack just fine.

![Screenshot_2](https://user-images.githubusercontent.com/85106934/120202878-693c3a80-c227-11eb-80a2-92a99a03ea56.png)
![Screenshot_3](https://user-images.githubusercontent.com/85106934/120202881-69d4d100-c227-11eb-9a6c-2b114a8afb13.png)

4) Is the issue repeatable?
 Yes.

5) Do you know a possible fix for the issue?
None whatsoever.

**Comment by Shorepion** [comment]
Did you changed the directory manually and forgot to adapt it within the launcher?
The default directory should have the path "Curse\Minecraft\Instances\Magica Infinitum III -..." but its currently "D:\Games\CurseForgeCraft\Install.."

Also the new 1.16.5 update is out, you might try this and install it to a "Update to new profile"

**Comment by thisisprobablyleo** [comment]
All my other modpacks work just fine, but the new pack works wonderfully, thanks for updating it! :D
