### ISSUE TITLE
Watchdog Timeout Crashes Server after Travel to Nether

### ISSUE THREAD

**Issue by jamcgee** [Shorepion/Magica-Infinitum-III#12]
> 1) Which Modpack version are you using?

MI3-3.3.0_SERVER.zip

> 2) Link to the crashlog (found in the crash-reports folder).

- [crash-2021-06-03_15.46.38-server.txt](https://pastebin.com/puM0gmEN)
- [crash-2021-06-03_15.52.18-server.txt](https://pastebin.com/tT8KbMjF)
- [crash-2021-06-03_16.29.48-server.txt](https://pastebin.com/gN2hJ9TF)
 
3) Detailed description of the issue and if possible pls attach images

Placed a nether portal and walked through.  First crash occurred within a minute or two (before any actual exploration occurred).  Subsequent crashes occurred immediately upon the character rejoined the server.

**Note:** This is crashing the *server*, not the client.  The client can freely rejoin the server once the server is restarted (and promptly crash it).

4) Is the issue repeatable?

I don't know how the condition was initially created, but at this point the world (or at least the associated character) is wedged.

5) Do you know a possible fix for the issue?

Negative.  Unknown cause for the fault.

**Comment by jamcgee** [comment]
> 4) Is the issue repeatable?

Yes.  Loaded a backup from prior to lighting the portal.  Each time the Nether is entered from that location, the server watchdog would trigger within a minute.

```
[03Jun2021 17:48:55.721] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: BufGMux has made the advancement [We Need to Go Deeper]
[03Jun2021 17:48:55.777] [Server thread/WARN] [net.minecraft.server.MinecraftServer/]: Can't keep up! Is the server overloaded? Running 2499ms or 49 ticks behind
[03Jun2021 17:50:05.179] [Server Watchdog/FATAL] [net.minecraft.server.dedicated.ServerHangWatchdog/]: A single server tick took 60.00 seconds (should be max 0.05)
[03Jun2021 17:50:05.179] [Server Watchdog/FATAL] [net.minecraft.server.dedicated.ServerHangWatchdog/]: Considering it to be crashed, server will forcibly shutdown.
```

**Comment by Shorepion** [comment]
I was able to replicate the issue on a different world created throught the server pack. Looking for a fix now. Thats definetly a bug causing the server to crash. Thank you for the report!

**Comment by Shorepion** [comment]
JourneyMap was causing the trouble.
1) Remove the file "journeymap-1.16.5-5.7.1.jar" from the mods folder
2) Delete journeymap folder generated from the mod

I will upload a new ServerPack.zip for 3.3.0

**Comment by Shorepion** [comment]
JourneyMap was causing the trouble.
There will come a new 3.3.1 update with a fix for that very soon

**Comment by Shorepion** [comment]
Rats Mod was causing the issue. 
I just uploaded a Server Pack fix : https://www.curseforge.com/minecraft/modpacks/magica-infinitum-iii/files/3348399
If you want to play on a server without having problems entering the Nether, you have to remove Rats mod from your client instance aswell
