### ISSUE TITLE
Error: java.lang.IllegalStateException: Pose stack not empty

### ISSUE THREAD

**Issue by Fenrick1** [Shorepion/Magica-Infinitum-III#13]
Thank you for reporting an issue!
Please make sure to give answers for the following:

1) Which Modpack version are you using?
3.3.2
 
2) Link to the crashlog (found in the crash-reports folder).
That should be the right link : https://pastebin.com/gKFMXmnw

3) Detailed description of the issue and if possible pls attach images
I was mining ore blocks with a pretty efficient netherite pickaxe that also gave me experience boost each time I break a block with it. It then shut down while saving. I can't access the file anymore so it's impossible for me to get a picture of what is going on in my world.

4) Is the issue repeatable?
I don't know. I can make it happen again and again by trying to join the world but it doesn't change anything

5) Do you know a possible fix for the issue?
That's a good question, pal. Maybe I got too much xp or maybe too much blocks? It's talking about a pose stack but I don't know if it's a stack of blocks or just something else.

**Comment by Shorepion** [comment]
assistance via discord:
-deleting the playerdata and updating to latest version (3.3.3) fixed the issue
