### ISSUE TITLE
Server Crash When Fighting Ice Dragon

### ISSUE THREAD

**Issue by evanrinne** [Shorepion/Magica-Infinitum-III#14]
Thank you for reporting an issue!
Please make sure to give answers for the following:

1) Which Modpack version are you using?
 3.3.2

2) Link to the crashlog (found in the crash-reports folder).
https://pastebin.com/49gGaTbX
https://pastebin.com/3FNxxfds
 
3) Detailed description of the issue and if possible pls attach images
Server would crash when the ice dragon attacked a  player/mob. Fought 2 near each other, both would cause the server to crash.
 
4) Is the issue repeatable?
We think so, I had to remove the dragon from the area so the player could log in, but it happened every time they would join and the dragon attacked.
 
5) Do you know a possible fix for the issue?
No

**Comment by Shorepion** [comment]
https://github.com/Alex-the-666/Ice_and_Fire/issues

**Comment by Shorepion** [comment]
sorry can't do much about it. I linked this issue to the Ice and Fire Issue GitHub.

**Comment by Shorepion** [comment]
Im running the latest Java Edition (you are running an older version due to crash report) and it only crashes when are too much dragons. 1, 2 can be handled by the server

**Comment by Shorepion** [comment]
Can you try running the latest java edition (you are currently running 271, latest is 301.
There is a guide on how to set up the launcher running the latest java:
Scroll down to performance:

**Comment by Shorepion** [comment]
Can you try running the latest java edition (you are currently running 271, latest is 301.
There is a guide on how to set up the launcher running the latest java:
Scroll down to performance:
https://www.curseforge.com/minecraft/modpacks/magica-infinitum-iii

**Comment by evanrinne** [comment]
> Can you try running the latest java edition (you are currently running 271, latest is 301.
> There is a guide on how to set up the launcher running the latest java:
> Scroll down to performance:
> https://www.curseforge.com/minecraft/modpacks/magica-infinitum-iii

I will give it a shot, thanks for responding.

**Comment by Shorepion** [comment]
mod got updated and the issue ahould be fixed due to mod author
