### ISSUE TITLE
can't install the modpack can't find addon

### ISSUE THREAD

**Issue by idk188** [Shorepion/Magica-Infinitum-III#15]
Thank you for reporting an issue!
Please make sure to give answers for the following:

1) Which Modpack version are you using?
 3.3.3.3

3) Detailed description of the issue and if possible pls attach images
 
![image](https://user-images.githubusercontent.com/9683375/130374848-62589bfb-5dfe-4c4d-a673-c9f2ed370c8b.png)

4) Is the issue repeatable?
  everytime I try to install that modpack

5) Do you know a possible fix for the issue?
it might because it can't find this
https://www.curseforge.com/minecraft/mc-mods/mana-and-artifice 
it has the same project id

**Comment by Shorepion** [comment]
Hello,
CurseForge is having trouble with the Launcher currently. They are working to fix this as soon as possible.
If you dont want to wait for the fix you can use the GDLauncher and install the modpack (under CurseForge category). On top of that add angelring () and mana and artifice ().
Regards

**Comment by Shorepion** [comment]
Hello,
CurseForge is having trouble with the Launcher currently. They are working to fix this as soon as possible.
If you dont want to wait for the fix you can use the GDLauncher and install the modpack (under CurseForge category). On top of that add angelring (angelring-1.16.5-1.3.4.1.jar) and mana and artifice (mana-and-artifice-1.3.0.6.jar).
Regards
