### ISSUE TITLE
Two Silver Ores/Bars

### ISSUE THREAD

**Issue by Gafgarion37** [Shorepion/Magica-Infinitum-III#2]
Thank you for reporting an issue!
Please make sure to give answers for the following:

1) Which Modpack version are you using?
MI3-3.1.0
 
2) Link to the crashlog (found in the crash-reports folder).
No crashlog
 
3) Detailed description of the issue and if possible pls attach images
Both Allomancy and Silent Gem's 3 have a silver ore and bar. If it is possible to have them use the same silver, I would suggest that.
 
4) Is the issue repeatable?
Yes
 
5) Do you know a possible fix for the issue?
No

**Comment by Shorepion** [comment]
Allomancy shouldnt be enabled in 3.1.0 (see Changelog). 
I think you are talking about Ice and Fire silver.

I already added a convert feature in the next update (https://www.curseforge.com/minecraft/mc-mods/auto-ore-dictionary-converter).
