### ISSUE TITLE
Difficult/impossible to progress in Evilcraft

### ISSUE THREAD

**Issue by Cathbell** [Shorepion/Magica-Infinitum-III#21]
Hello

First off, I want to say I love this modpack. There's not a whole lot of modpacks out there using and focusing exclusively on magic so... Awesome and thank you !

Now, onto the bug... Perhaps you've already noticed it or something but anyway... I'm using the version 3.3.7 by the way.
 
The issue is that, it's difficult if down right near impossible to progress in Evilcraft because of the crushed dark gems... The only way to get them is to trade them with a werewolf NPC exclusive to the Evilcraft mod and I can't find any.

It would be easier to have either the alchemist table from Blood magic or the Crusher from Occultism transform the dark gems into crushed dark gems... or something.

Thanks

P.S : By the way, I've put this under bug but I'm not sure if it's one or not, really... I mean, I haven't played the Evilcraft mod solo so perhaps it's MEANT to be hard to get crushed dark gems...

**Comment by Shorepion** [comment]
Hello,
thank you for the kind words!
Crushed dark gem have little chance to be dropped by mining dark ore (Fortune increases drop chances).

**Comment by Cathbell** [comment]
I did not know that ! Or maybe I'd just forgotten... Thank you for the tip !
