### ISSUE TITLE
jjei doesnt show at al;l and I clicked the recipe from the book and it crashed

### ISSUE THREAD

**Issue by Solartile** [Shorepion/Magica-Infinitum-III#22]
*Thank you for reporting an issue!
Please make sure to give answers for the following:*

## 2) Link to the crashlog (found in the crash-reports folder).
 *Don't post whole crashlogs directly in here!
 I recommend to use pastebin for the crashlogs: https://pastebin.com/*
 https://pastebin.com/3mygYZuH

**Comment by Shorepion** [comment]
Can you give a more detailed description pls - what exactly did you do before it crashed?

Did you clicked inside the ftb questbook to look up a recipe?
If yes, does it crash for every recipe or just one specific one?

**Comment by Shorepion** [comment]
closing due to unactivity.
