### ISSUE TITLE
Error 255

### ISSUE THREAD

**Issue by Pandragocorn** [Shorepion/Magica-Infinitum-III#23]
*Thank you for reporting an issue!
Please make sure to give answers for the following:*

## 1) Which Modpack version are you using?

Magica Infinitum III - 1.16.5-3.3.8.zip
 
## 2) Link to the crashlog (found in the crash-reports folder).

https://pastebin.com/RHQgF1bm
 
## 3) Detailed description of the issue and if possible pls attach images

following a line stating `Failed to start Minecraft`and a multitude of lines of code in red, the following is stated; 
`[10:56:12][main/INFO] [STDOUT/]: [org.multimc.EntryPoint:main:37]: Exiting with -1
Process exited with code 255.`
 
The FML early loading process briefly shows up before being exited due to the line below

## 4) Is the issue repeatable?
 
This issue occurs every time I attempt to launch the modpack

## 5) Do you know a possible fix for the issue?

None

**Comment by Shorepion** [comment]
The modpack is not build with MultiMC and is not intended to work properly with MI3, which can bring up (launching) issues. Please use the official CurseForge Launcher (or GDLauncher which works aswell due to reports from other players).
