### ISSUE TITLE
Energy Relay Mk 2 uses an Energy Relay Mk 2 as a crafting ingredient

### ISSUE THREAD

**Issue by SekhetBR** [Shorepion/Magica-Infinitum-III#24]
Most recent version of the pack, no mod additions or subtractions. 

*Thank you for reporting an issue!
Please make sure to give answers for the following:*

## 2) Link to the crashlog (found in the crash-reports folder).
 *Don't post whole crashlogs directly in here!
 I recommend to use pastebin for the crashlogs: https://pastebin.com/*

**Comment by Shorepion** [comment]
My bad! Thank you for the hint. Will be fixed in the next update.
