### ISSUE TITLE
Vampire forest not generating

### ISSUE THREAD

**Issue by Satacon** [Shorepion/Magica-Infinitum-III#3]
Thank you for reporting an issue!
Please make sure to give answers for the following:

1) Which Modpack version are you using?
Magica Infinitum III 1.16.3 version  3.10

2) Link to the crashlog (found in the crash-reports folder).
 Don't post whole crashlogs directly in here!
 I recommend to use pastebin for the crashlogs: https://pastebin.com/
 
No Crashlog

3) Detailed description of the issue and if possible pls attach images

When creating a world with the preset settings for worldgen, no Vampire forests generate. I was able to get them to generate using default world type, but I have a server running the biomes o plenty world type. I'm trying to get the Vampire Forest to generate in Biomes o' Plenty. I've dug through the config files and cannot a solution to the issue.
![image](https://user-images.githubusercontent.com/50927834/103247797-c147db80-492d-11eb-9c44-9e95a41d2498.png)

4) Is the issue repeatable?
 
Yes

5) Do you know a possible fix for the issue?

**Comment by Shorepion** [comment]
I tried to find it aswell but couldn't - thats indeed a problem, since you need to have one for the mod progression.
Im not sure if they just dont generate or they are just insanley rare (maybe somehow influenced by BoP mainly).
Its on my to do list. 
Thanks for the report.

**Comment by Shorepion** [comment]
https://github.com/Glitchfiend/BiomesOPlenty/issues/1774#issuecomment-752237278

**Comment by Shorepion** [comment]
Glitchfiend/BiomesOPlenty#1774 (comment)
