### ISSUE TITLE
Item Stacking Discrepency - 1.16.3-3.1.0

### ISSUE THREAD

**Issue by haku-81** [Shorepion/Magica-Infinitum-III#4]
For some reason, certain items upon being picked up refuse to stack unless placed in the main inventory(Off the Hotbar) and then sorted using the inventory sorter. This causes a large problem as these unstacking items refuse to go into drawers unless the drawer is emptied and the items sorted in the inventory, then put back inside.

This bug is most notable with crops such as wheat, carrots and potatoes. I've not been able to progress very far in the modpack, as this is actually quite the infuriating bug, but i suspect this would have significant effects on whatever automations you might attempt to build, even clogging storage systems. The amount of micromanaging this single bug causes has rendered the entire modpack unplayable to me.

**Comment by Shorepion** [comment]
I couldnt replicate this bug.

Tried it in multiple scenarios: 
1) Bonemealed crops and harvested
2) Let the crops grow with ring of farmer and harvested
3) throwed crops on ground and picked them up
4) put them in chest, destroyed chests and picked the items up
5) splittet items in inventory and used the auto sort (middle mouse click)
6) splitted items in invenory and stacked them toghether by hand one by one (+using double left click with holded stack)
7) put them in storage drawers and get back single items and stacks

In none of these cases the items seemed to have stacking issues. Everything looked normal.
Are you able to make a video where you show the issue?

**Comment by haku-81** [comment]
Infinitum 3 Bug.mkv
<https://drive.google.com/file/d/1jxn0xp5ouqYDEx33-xN3DaXpmbFNgT0W/view?usp=drive_web>
Ok, this is very confusing, but I think I got it.

So here's the video, and i wanted to test some things, so i tried
replicating it in a creative world, entering survival mode obviously. And
it didn't work. I even just waited until some carrots grew naturally.
Didn't work, they just stacked normally.

HOWEVER, when I went back to my survival world, I harvested some crops
again, and they stacked normally all of a sudden. I kept doing it, and by
chance I figured out what triggers this bug.

If I harvest carrots or other crops while HOLDING any crop in my hand, it
won't stack properly. However if I break the crop with left click or use an
empty hand or a tool/bone meal, whatever, then they stack fine. No idea why
any of this is a thing, but that's what's going on as far as I can tell.
You can see in the video, while I harvest the carrots, I'm also HOLDING
carrots in my hand.

**Comment by Shorepion** [comment]
Ok, now with your detailed description I was able to replicate this issue.
I think its a bug with "reap mod".
It is fixed in the upcoming update, but my uploaded file is "Under Review" since 4 days now. Cant tell when it got accepted.
![underreview](https://user-images.githubusercontent.com/24994890/103317134-e40bea00-4a2a-11eb-8f75-fa4bbea5b19c.JPG)

You can manually fix it by adding the "harvest mod" to the mods folder (https://www.curseforge.com/minecraft/mc-mods/harvest/files/3087381)

**Comment by haku-81** [comment]
Yep, that fixed it. Thanks for the help, and this weird bug aside, really
excited to get into the modpack. It was exactly what I was craving.


On Dec 29, 2020 at 2:10 PM, Shorepion <notifications@github.com> wrote:

Ok, now with your detailed description I was able to replicate this issue.
I think its a bug with "reap mod".
It is fixed in the upcoming update, but my uploaded file is "Under Review"
since 4 days now. Cant tell when it got accepted.
[image: underreview]
<https://user-images.githubusercontent.com/24994890/103317134-e40bea00-4a2a-11eb-8f75-fa4bbea5b19c.JPG>

You can manually fix it by adding the "harvest mod" to the mods folder (
https://www.curseforge.com/minecraft/mc-mods/harvest/files/3087381)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Shorepion/Magica-Infinitum-III/issues/4#issuecomment-752257890>,
or unsubscribe
