### ISSUE TITLE
Crash Issue

### ISSUE THREAD

**Issue by HexHaunter** [Shorepion/Magica-Infinitum-III#6]
Thank you for reporting an issue!
Please make sure to give answers for the following:

1) Which Modpack version are you using?
3.1.1Z for 1.16.3
 
2) Link to the crashlog (found in the crash-reports folder).
https://pastebin.com/NmK0phw4
 
3) Detailed description of the issue and if possible pls attach images
 Was playing fine as a single player and occasional LAN with my brother for a few days. Tried to use the config option for Corail
Tombstone in the Mods tab on the home screen and the game crashed. Since then I've been unable to load the world I was playing on.

4) Is the issue repeatable?
 I was able to make a new world, quit and reload several times, but I can't get into my old world at all.

5) Do you know a possible fix for the issue?
Not sure, I've tried reinstalling the mod pack, restarting my computer, etc. but I haven't figured it out yet. Thanks in advance for your help.

**Comment by Shorepion** [comment]
I cant really figure out how the crash occured. The crashlog also doesnt really match with the 'corail tombstone config crash'.
What I read from it, there is something related to the plague doctor (rats mod) and/or cssting spell with wand (elements of power mod).
Is it possible thats something to do with these mods?
Can you give some more detailed description concerning this matter?

**Comment by HexHaunter** [comment]
We had a Plague Doctor in our village, but he died in an illager raid, but I had been able to quit and load the game after this happened. We had gathered some ore drops from elements of power, but hadn't actually crafted anything from the mod.

**Comment by Shorepion** [comment]
What you can try to do is start your world as server and run the /killall command, trying to get rid of the plague docs or other corrputed entities/mobs
