### ISSUE TITLE
You need a mod that fix the generation

### ISSUE THREAD

**Issue by NiceClown** [Shorepion/Magica-Infinitum-III#7]
You need a mod that fix the generation
![javaw_BFrQNR2QH8](https://user-images.githubusercontent.com/73308198/107616150-8b9d4e80-6c5e-11eb-9e10-570a70327e50.png)
I suggest [this](https://www.curseforge.com/minecraft/mc-mods/save-my-stronghold)
But I'm afraid to install it, so as not to break something!)

**Comment by Shorepion** [comment]
Added this to the to do list. Thanks.
