### ISSUE TITLE
rat "nugget" renderer error - renderer missing?

### ISSUE THREAD

**Issue by cmndrOri** [Shorepion/Magica-Infinitum-III#8]
V 3.2.0, no update between no issue and issue appearing.

What it says in the title. I loaded my world today after everything was working fine yesterday and noticed that the rats and some of the rat mod stuff had pink box missing textures, then as I was walking across my base the world crashed. Tried to reload it, didnt even render the world just crashed again. Tried a complete fresh download of the pack, same result crash without even rendering blocks. Error says some rendering dependency is missing, but I haven't even changed the configs, let alone added or removed anything from the pack since... yunno, yesterday when it was running fine.

[Magica Infinitum III - Crash - Rat nugget renderer missing.txt](https://github.com/Shorepion/Magica-Infinitum-III/files/6013950/Magica.Infinitum.III.-.Crash.-.Rat.nugget.renderer.missing.txt)

**Comment by Shorepion** [comment]
Hey,

thats very weird. 
I see you arent running the latest JAVA Version. Please update to the latest one (update 281) and start the pack again.
If that doesnt help remove Rats and Ratlantis manually and start the pack.
For all testing purposes always use a back up of your world!

**Comment by cmndrOri** [comment]
Removing rats and reloading the world seems to have deleted whatever items were causing the problem, and adding them back to the pack still let it load. There's still some funkyness with rats and modded ores though, I'm pretty sure this issue happened after i fed one of my buddies orerats crimson iron ore.

**Comment by Shorepion** [comment]
ok. Im just want to make sure. Did you updated JAVA?

**Comment by Shorepion** [comment]
ok. I just want to make sure: Did you updated Java?

**Comment by Shorepion** [comment]
Ok. Did you updated Java?

**Comment by cmndrOri** [comment]
Should have added that, yea. I did update java and tried to open the world before removing rats, same crash on world rendering.

**Comment by Shorepion** [comment]
Can you provide the latest crash log pls.

**Comment by Shorepion** [comment]
Unfortunately I cant replicate this crash. Try to update the Rats mod manually by replacing the jar file in the instance folder.
https://www.curseforge.com/minecraft/mc-mods/rats/files/3189312 (v7.1.1).
