### ISSUE TITLE
Undergarden not generating foliage

### ISSUE THREAD

**Issue by VariantMouse** [Shorepion/Magica-Infinitum-III#9]
Thank you for reporting an issue!
Please make sure to give answers for the following:

This is occurring in version 1.16.4
 
The Undergarden dimension is loading the terrain itself properly, but there are no trees or plants anywhere in any of the biomes. I tried deleting the Undergarden dimension folder and uninstalling, then reinstalling the mod itself, and that didn't fix anything. I did some checking on the github page for the Undergarden and there is a similar issue which results from an unspecified conflict between Undergarden and Immersive Engineering, which is not in the pack, of course, but my guess would be that this may be an issue involving a conflict with another mod, though I have no earthly idea which one.

**Comment by Shorepion** [comment]
Seems like there is a conflict with Biomes O' Plenty. Starting a world with worldtype "Default" fixed it.
Will investigate a little more.
